### ISSUE TITLE
python version

### ISSUE THREAD

**Issue by dvdrbls** [aaronpenne/generative_art#2] opened 2019-04-13 20:30 UTC
Hi Thanks for sharing this repo,  how do I tell processing that I have two versions of python, which one has to be used in order to work, 

for every script i have this message

console: Failed to install '': java.nio.charset.UnsupportedCharsetException: cp0.

thanks!

**Comment by aaronpenne** [comment] 2019-04-14 17:25
Thanks for checking it out! Looks like a Java issue to me, more here: https://github.com/jdf/Processing.py-Bugs/issues/158

I would try to reinstall Processing then reinstall Python mode. Sorry I can't be of more help on this, I've only ever used it out of the box. Closing as the issue isnl not with the code. Good luck, keep us posted on the solution!

**Closed by aaronpenne** 2019-04-14 17:25 UTC
